title: MAH Architects Inc.
description: MAH Architects Inc. is an Ontario-based architecture firm offering residential, commercial, and institutional designs.
baseurl: "" # Leave blank for GitHub Pages at root, else '/branch'
url: "https://maharch.muxday.com" # https:// + Domain or GitHub Pages URL
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Markdown processing
markdown: kramdown
theme: minima  # optional fallback theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
